
GET http://localhost:4000/services HTTP/1.1
content-type: application/json

### Get Service by service ID
GET http://localhost:4000/services/25db8546-b2fb-45b6-9704-3002421450ed HTTP/1.1
content-type: application/json

### Add a new service

POST http://localhost:4000/services HTTP/1.1
content-type: application/json

{
  "name": "Service 1",
  "description": "Description of Service 1"
}

### Add a task to a service
POST http://localhost:4000/services/25db8546-b2fb-45b6-9704-3002421450ed/tasks HTTP/1.1
content-type: application/json

{
  "name": "Task 1",
  "description": "Description of Task 1",
  "status": "pending"
}